import { ContentSlide } from '../../components/slides'
import { DayDeck } from '../../presentation/DayDeck'
import { courseDays } from '../../presentation/course'

const vanillaCounter = ['let count = 0', 'button.addEventListener("click", () => {', '  count += 1', '  button.textContent = "Count: " + count', '})'].join('\n')
const earlyReact = ['var Counter = React.createClass({', '  getInitialState: function () { return { count: 0 }; },', '  render: function () {', '    return <button>Count: {this.state.count}</button>;', '  }', '});'].join('\n')
const modernCounter = ['function Counter() {', '  const [count, setCount] = useState(0)', '  return <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>', '}'].join('\n')
const classCounter = ['class Counter extends React.Component {', '  state = { count: 0 }', '  render() { return <button onClick={() => this.setState({ count: this.state.count + 1 })}>', '    Count: {this.state.count}</button> }', '}'].join('\n')

export function Day03() {
  return (
    <DayDeck day={courseDays[2]} titleNotes="Reconnect to Day 2's final question: what if we describe UI rather than issue every DOM instruction? Timing: 1 minute.">
      <ContentSlide eyebrow="Yesterday · vanilla JavaScript" title="When count changes, what happens?" notes="ASK: What automatically changes when count becomes 1? WAIT FOR: nothing. EXPLAIN: our code must still find and update the DOM. TIMING: 2 minutes."><pre className="lesson-code compact"><code>{vanillaCounter}</code></pre></ContentSlide>
      <ContentSlide eyebrow="A different question" title="What if we described the UI for the current state?" notes="ASK: What if we stated the desired button for count = 1 instead of which node to edit? EXPLAIN: declarative UI. React did not invent it; it made the model popular on the web. TIMING: 2 minutes."><div className="declarative-compare"><div><p className="column-label">IMPERATIVE</p><code>find button<br />change its text</code></div><div><p className="column-label">DECLARATIVE</p><code>count: 1<br />→ &lt;button&gt;Count: 1&lt;/button&gt;</code></div></div></ContentSlide>
      <ContentSlide eyebrow="The doorway" title="Describe the result, not the DOM edits" notes="EXPLAIN: For the same state, the function describes the same UI. Changing state means asking again what UI should be. TRANSITION: Enter React. TIMING: 1 minute."><p className="function-of-state">UI = f(state)</p></ContentSlide>
      <ContentSlide eyebrow="History · concise" title="React became public in 2013" notes="EXPLAIN: React was open-sourced on May 29, 2013. Jordan Walke is credited by the React team as its original creator. FUN FACT: the initial public release commit is linked from react.dev/versions. TIMING: 1.5 minutes."><div className="react-history"><span><b>2011-ish</b>internal origins</span><span><b>2012</b>Instagram adoption</span><span><b>May 2013</b>open sourced</span></div></ContentSlide>
      <ContentSlide eyebrow="React, circa 2013" title="It did not start with Hooks" notes="EXPLAIN: This is historical React. createClass provided component definitions and getInitialState supplied component state. Do not use it for new code. TIMING: 2 minutes."><pre className="lesson-code historic-code"><code>{earlyReact}</code></pre></ContentSlide>
      <ContentSlide eyebrow="React today" title="The same idea, with modern syntax" notes="ASK: What visibly changed? WAIT FOR: function, useState, less ceremony. EXPLAIN: syntax evolved; state in, UI description out remains. The detailed history comes later in the timeline. TIMING: 1.5 minutes."><pre className="lesson-code compact"><code>{modernCounter}</code></pre></ContentSlide>
      <ContentSlide eyebrow="Structure" title="What is a component?" notes="EXPLAIN: A component owns or describes one piece of UI. An application composes components, rather than one giant page script. TIMING: 2 minutes."><div className="component-tree"><strong>App</strong><div><span>Header</span><span>Sidebar</span><span>ProductList</span><span>Cart</span></div><div className="component-leaves"><span>ProductCard</span><span>ProductCard</span><span>ProductCard</span></div></div></ContentSlide>
      <ContentSlide eyebrow="Mental model" title="Inputs + memory → UI description" notes="EXPLAIN: Props are parent-supplied inputs. State is component memory. They are separate inputs to render; neither turns into the other. Render uses both to describe UI. TIMING: 2 minutes."><div className="component-model"><div><span>props</span><b>+</b><span>state</span></div><i>↓</i><strong>render</strong><i>↓</i><em>UI description</em></div></ContentSlide>
      <ContentSlide eyebrow="Question" title="This looks like HTML inside JavaScript. Is it?" notes="ASK: Vote before revealing. EXPLAIN: JSX is syntax that produces React elements. JSX is not HTML; a React element and component are not DOM elements. TIMING: 2 minutes."><div className="jsx-reveal"><code>const element = &lt;h1&gt;Hello, Selva&lt;/h1&gt;</code><i>↓</i><code>React.createElement(&quot;h1&quot;, null, &quot;Hello, Selva&quot;)</code></div></ContentSlide>
      <ContentSlide eyebrow="Conceptually" title="What happens when React renders?" notes="EXPLAIN: A component produces React elements. React determines what the target renderer should do. React DOM targets browser DOM. No Fiber internals today. TIMING: 2 minutes."><div className="react-pipeline"><span>Component</span><i>↓</i><span>render</span><i>↓</i><span>React elements</span><i>↓</i><span>reconciliation</span><i>↓</i><span>React DOM</span><i>↓</i><span>DOM</span><i>↓</i><span>browser → pixels</span></div></ContentSlide>
      <ContentSlide eyebrow="Two conceptual phases" title="Render decides. Commit applies." notes="EXPLAIN: Render determines what the UI should be. Commit applies needed changes to the host environment, here the DOM. More accurate than ‘React redraws only what changed.’ TIMING: 2 minutes."><div className="phase-cards"><div><b>RENDER</b><span>determine the next UI</span></div><div><b>COMMIT</b><span>apply needed DOM changes</span></div></div></ContentSlide>
      <ContentSlide eyebrow="Prediction" title="Does React throw away the whole list?" notes="ASK: Given before and after, what changes? WAIT FOR: B becomes C. EXPLAIN: reconciliation relates previous and next trees before committing DOM changes. Mention identity: type, position, keys. Source: legacy.reactjs.org/docs/reconciliation.html. TIMING: 2 minutes."><div className="reconcile-example"><div><p className="column-label">BEFORE</p><code>&lt;li&gt;A&lt;/li&gt;<br />&lt;li&gt;B&lt;/li&gt;</code></div><i>→</i><div><p className="column-label">AFTER</p><code>&lt;li&gt;A&lt;/li&gt;<br />&lt;li&gt;C&lt;/li&gt;</code></div></div></ContentSlide>
      <ContentSlide eyebrow="The class era" title="Classes gave components stateful behavior" notes="EXPLAIN: Class components were an important, successful model and remain supported. props is this.props; state is this.state; updates use this.setState; render returns UI. Today, functions are recommended for new code. TIMING: 2 minutes."><pre className="lesson-code class-code"><code>{classCounter}</code></pre></ContentSlide>
      <ContentSlide eyebrow="Lifecycle · simplified" title="Components mount, update, and unmount" notes="ASK: Why care when a component enters or leaves UI? WAIT FOR: subscriptions, timers, cleanup. EXPLAIN: componentDidMount started work; componentDidUpdate responded to relevant changes; componentWillUnmount cleaned up. Some older lifecycle methods are legacy/unsafe. Source: react.dev/reference/react/Component. TIMING: 2.5 minutes."><div className="lifecycle-timeline"><div><b>MOUNT</b><span>constructor → render → componentDidMount</span></div><div><b>UPDATE</b><span>render → componentDidUpdate</span></div><div><b>UNMOUNT</b><span>componentWillUnmount</span></div></div></ContentSlide>
      <ContentSlide eyebrow="Function components" title="Props in. UI description out." notes="EXPLAIN: This is a plain function component. Historically, functions did not have component state and lifecycle capabilities in the same way classes did. Explain the class-era trade-offs here: related logic could spread across lifecycle methods; sharing stateful behavior often used HOCs or render props; and this/binding added JavaScript complexity. Classes were not bad. TRANSITION: How could a function remember? TIMING: 2 minutes."><pre className="lesson-code compact"><code>{['function Greeting({ name }) {', '  return <h1>Hello, {name}</h1>', '}'].join('\n')}</code></pre></ContentSlide>
      <ContentSlide eyebrow="Hooks" title="Functions learned to remember" notes="EXPLAIN: Hooks were announced in 2018 and shipped in React 16.8 in February 2019. Teach only useState: component state. useEffect synchronizes with external systems. Source: legacy.reactjs.org/blog/2019/02/06/react-v16.8.0.html. TIMING: 2 minutes."><div className="hook-explainer"><pre className="lesson-code compact"><code>{['const [count, setCount] = useState(0)', 'setCount(c => c + 1)'].join('\n')}</code></pre><p><b>useState</b> → component memory<br /><b>useEffect</b> → external synchronization</p></div></ContentSlide>
      <ContentSlide eyebrow="A careful bridge" title="Effects are not lifecycle methods in disguise" notes="EXPLAIN: The class lifecycle trio can help with migration, but the better model is that an Effect synchronizes with something outside React and may clean up that synchronization. Source: react.dev/learn/lifecycle-of-reactive-effects. TIMING: 2 minutes."><div className="effect-bridge"><div><p className="column-label">CLASS</p><code>componentDidMount()<br />componentDidUpdate()<br />componentWillUnmount()</code></div><div><p className="column-label">FUNCTION</p><code>useEffect(() =&gt; &#123;<br /> subscribe()<br /> return unsubscribe<br />&#125;, [...])</code></div></div></ContentSlide>
      <ContentSlide eyebrow="Live · predict" title="Do two counters share a count?" notes="ASK: Shared or independent? DEMO: Extract Counter, render it twice, and click each. EXPLAIN: each rendered component instance has its own state. Optional: add a third Counter. TIMING: 3 minutes."><pre className="lesson-code compact"><code>{['function Counter() { /* stateful button */ }', '', 'export default function App() {', '  return <><Counter /><Counter /></>', '}'].join('\n')}</code></pre></ContentSlide>
      <ContentSlide eyebrow="Connect all three days" title="What happened when we clicked?" notes="EXPLAIN: Day 1 supplied pixels; Day 2 supplied JavaScript, events, and DOM; React coordinates the state-to-UI relationship. KEY TAKEAWAY: setCount does not mutate the button directly. TIMING: 2 minutes."><div className="click-pipeline"><span>CLICK</span><i>↓</i><span>event handler</span><i>↓</i><span>setCount</span><i>↓</i><span>React schedules update</span><i>↓</i><span>render → elements → reconcile → commit</span><i>↓</i><span>DOM → browser → PIXELS</span></div></ContentSlide>
      <ContentSlide eyebrow="Evolution, not a replacement ladder" title="React’s programming model kept evolving" notes="EXPLAIN: Dates are anchors, not release notes: createClass, classes, React 16/Fiber, Hooks/16.8, React 18, React 19. Official versions currently list React 19.3 as latest. Source: react.dev/versions. TIMING: 2 minutes."><div className="react-evolution"><span><b>2013</b>createClass</span><span><b>2015+</b>classes</span><span><b>2017</b>React 16 / Fiber</span><span><b>2018–19</b>Hooks / 16.8</span><span><b>2022</b>React 18</span><span><b>2024–26</b>React 19 · 19.3 current</span></div></ContentSlide>
      <ContentSlide eyebrow="Bring it together" title="What React is—and is not" notes="EXPLAIN: React is a library for building user interfaces from components. It is not a browser, JavaScript, HTML, the DOM, or a complete application framework. React DOM is the browser renderer. TIMING: 2 minutes."><div className="react-today"><div><p className="column-label">REACT IS NOT</p><span>a browser · JavaScript · HTML · the DOM · a whole app framework</span></div><div><p className="column-label">REACT IS</p><strong>a UI library built from components</strong></div></div></ContentSlide>
      <ContentSlide eyebrow="Tomorrow" title="Components are only the beginning" notes="ASK: What questions appear building a whole application? WAIT FOR: shared state, communication, data fetching, forms, navigation, hundreds of components. TRANSITION: Day 4 — Building with React. TIMING: 1.5 minutes."><div className="next-questions"><span>Where does state live?</span><span>How do components communicate?</span><span>How do we fetch data?</span><span>How do we structure an app?</span></div></ContentSlide>
    </DayDeck>
  )
}
